---
linters:
  enable-all: true
  disable:
    - exhaustruct     # structs may be uninitialized
    - nlreturn        # covered by wsl cuddle rules
    - goimports       # conflicts with GCI
    - nonamedreturns  # named returns are acceptable in short functions
    # deprecated
    - gomnd
    - execinquery

severity:
  default-severity: major

issues:
  exclude-use-default: false
  exclude-case-sensitive: true
  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoglobals
        - errcheck
        - wrapcheck
        - gosec
        - goerr113

linters-settings:
  depguard:
    rules:
      main:
        list-mode: strict
        allow:
          - $gostd
          - github.com/go-openapi
          - github.com/gorilla/mux
          - github.com/prometheus/alertmanager
          - github.com/Masterminds/sprig/v3
          - gitlab.com/slxh/go/env
          - gitlab.com/slxh/go/slogutil
          - gitlab.com/slxh/matrix/alertmanager_matrix
          - gitlab.com/slxh/matrix/bot
          - maunium.net/go/mautrix

  gci:
    sections:
      - standard
      - default
      - localmodule

  gosec:
    excludes: []

  govet:
    enable-all: true

  mnd:
    ignored-numbers:
      - '8'
      - '16'
      - '32'
      - '64'
      - '10'

  nolintlint:
    require-explanation: true

  paralleltest:
    ignore-missing: true

  revive:
    enable-all-rules: true
    rules:
      # conflicts with mnd
      - name: add-constant
        disabled: true
      # named returns are acceptable in short functions
      - name: bare-return
        disabled: true
      # conflicts with lll
      - name: line-length-limit
        disabled: true
      # conflicts with errcheck
      - name: unhandled-error
        disabled: true

  stylecheck:
    checks: [all]

  varnamelen:
    min-name-length: 1
