---
version: "2"

severity:
  default: major

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - '^\\.go$'
      - third_party$
      - builtin$
      - examples$

linters:
  default: all
  disable:
    - exhaustruct     # structs may be uninitialized
    - nlreturn        # covered by wsl cuddle rules
    - nonamedreturns  # named returns are acceptable in short functions
    - funcorder       # functions are allowed in any order
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/go-openapi
            - github.com/gorilla/mux
            - github.com/prometheus/alertmanager
            - github.com/Masterminds/sprig/v3
            - gitlab.com/slxh/go/env
            - gitlab.com/slxh/go/slogutil
            - gitlab.com/slxh/matrix/alertmanager_matrix
            - gitlab.com/slxh/matrix/bot
            - gopkg.in/yaml.v3
            - maunium.net/go/mautrix
    govet:
      enable-all: true
    mnd:
      ignored-numbers:
        - "8"
        - "16"
        - "32"
        - "64"
        - "10"
    nolintlint:
      require-explanation: true
    paralleltest:
      ignore-missing: true
    revive:
      enable-all-rules: true
      rules:
        # conflicts with mnd
        - name: add-constant
          disabled: true
        # named returns are acceptable in short functions
        - name: bare-return
          disabled: true
        # conflicts with lll
        - name: line-length-limit
          disabled: true
        # conflicts with errcheck
        - name: unhandled-error
          disabled: true
    staticcheck:
      checks:
        - all
    varnamelen:
      min-name-length: 1
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
          - errcheck
          - gochecknoglobals
          - gosec
          - wrapcheck
        path: _test\.go
      - linters: [staticcheck]
        text: QF1008  # Omit embedded fields from selector expression
    paths:
      - '^\\.go$'
      - third_party$
      - builtin$
      - examples$
